spring:
  application:
    name: api-gateway

server:
  port: 8080

# Service Configuration
BASE_AUTH_SERVICE_URL: ${BASE_AUTH_SERVICE_URL}
INTERNAL_SERVICE_SECRET: ${INTERNAL_SERVICE_SECRET}

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL}

resilience4j:
  circuitbreaker:
    instances:
      authService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true
  info:
    env:
      enabled: true
