spring:
  application:
    name: account-service

  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 60000
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      ssl:
        enabled: false

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

server:
  port: 8083

exchange:
  eur-to-usd: 1.16
  usd-to-eur: 0.86

# Async and RabbitMQ settings
async:
  core-pool-size: 8
  max-pool-size: 20
  queue-capacity: 100
  
rabbit:
  async:
    timeout: 5000  # 5 seconds
    core-pool-size: 4
    max-pool-size: 12